### ISSUE TITLE
How to add new ROMS

### ISSUE THREAD

**Issue by Diegus83** [Emulga/recalbox-es_systems.cfg#1]
Edit: Nevermind, I found the <core> tag in the gamelist.xml, I have looked before but I didn't realized not all entries have it. 

I'm using an image that comes with the amazing emulga theme and I can't figure out how to add a new ROM for one of the arcade systems.
I can see all the ROMs in the ARCADE folder but where do I set what core to use for the new ones? Do I have to set it one by one in the GUI?

Thanks in advance!

**Comment by gravelfreeman** [comment]
With search and replace with a software like code or sublime text you can change all the <cores> and <emulator> in one click! It's best to seperate your roms in different folders per core. Then batch edit <cores> and <emulator> and after merge all the different gamelist (ex mame078, mame138, mame4all, etc) into one gamelist.xml. Alphabetical order isn't important as RB will show it correctly afterwards in the frontend. Hope this helps.
